Data processing
NduatiKagiri/blog-webapp pull request #2
Opened 2022-09-21 23:44 UTC by NduatiKagiri

In this branch I:

- Included the associations in the models
- Added the following additional methods for the models.
    -  Users
        - A method that returns the 3 most recent posts for a given user.
    -  Posts
        - A method that updates the posts counter for a user.
        - A method which returns the 5 most recent comments for a given post.
    -  Comments
        - A method that updates the comments counter for a post.
    -  Likes
        - A method that updates the likes counter for a post.

2022-09-21 23:51 UTC, mikethreels requested changes
Hi John, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- linters are passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-21 23:51 UTC, mikethreels commented on app/models/user.rb
> +  has_many :likes
- [ ] the foreign keys should be set in these lines of code.

2022-09-21 23:51 UTC, mikethreels commented on app/models/post.rb
> +    User.find_by(User_id).update(posts_counter: total_posts + 1)
- [ ] [OPTIONAL] To make this a bit easier you might want to use the below code `user.increment!(:posts_counter)`

2022-09-22 01:59 UTC, BenMukebo approved these changes
### Hi @NduatiKagiri, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- The associations between models is set up correctly according to the given [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png).:heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL]  Please kindly update your `readme file` to reflect the changes for this milestone as this will make your `readme file` more informative and professional. Check out this [template](https://github.com/microverseinc/readme-template) and adapt it to your project. Replace all the information in the various sections of the template with information pertaining to your project. 

- The README file It is the first file a person will see when they encounter your project, so it should be fairly brief but detailed. It will make your project stand out from a bunch of others.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 01:59 UTC, BenMukebo commented on app/models/post.rb
> +  belongs_to :user
- [OPTiONAL] The associations between models must be set up correctly according to the given [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png). Which means 🤔 The Post belongs-to user through the `'author_id'` column of the Post table. Now, we need to show that, the  `'author_id'` reference  User class modal.
Your code should look like this:

```ruby
  # app/models/post.rb
  belongs_to :author, class_name: 'User'
```

2022-09-22 01:59 UTC, BenMukebo commented on app/models/like.rb
> +  belongs_to :user
- [OPTONAL] The same here 🤔 Likes belongs-to user through the `'author_id'` column of the Like table. Now, we need to show that, the  `'author_id'` reference  User class modal.
Your code should look like this 👇🏻 :

```ruby
 # app/models/like.rb
  belongs_to :author, class_name: 'User'
```

2022-09-22 01:59 UTC, BenMukebo commented on app/models/comment.rb
> +  belongs_to :user
- [OPTONAL] The same here 🤔  The Comments belongs-to user through the `'author_id'` column of the Comment table. Now, we need to show that, the  `'author_id'` reference  User class modal.
Your code should look like this 👇🏻 :

```ruby
  # app/models/comment.rb
  belongs_to :author, class_name: 'User'
```

2022-09-22 16:23 UTC, merged