Add Devise
NduatiKagiri/blog-webapp pull request #9
Opened 2022-10-13 17:39 UTC by NduatiKagiri

In this branch we:

- Removed current_user method in ApplicationController.
- [Installed and setup devise](https://github.com/heartcombo/devise#getting-started).
  - Can register a new user.
  - User logs in with a combination of email and password.
  - Hashed password should be stored in the database.
  - Ask for confirmation of email.
  - Can reset password.
- [Modified the views in devise](https://github.com/heartcombo/devise#configuring-views) for registration and login to match [the wireframes from the Sneak Peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md#:~:text=For%20this%20project%20you%20will%20have%20full%20freedom%20in%20terms%20of%20visual%20design%20but%20you%20will%20need%20to%20keep%20the%20following%20wireframes%3A) and your styling.

2022-10-13 23:27 UTC, BenMukebo requested changes
### Hi @NduatiKagiri,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️    
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ]  Please, add a meaningful  `Project description`. Remember A project description is a high-level overview of why you're doing a project. The document explains a project's objectives and essential qualities. Is an essential document that provides your audience with a comprehensive overview of the project. Think of it as the elevator pitch that focuses on what and why without delving into how. 😉 💯 

- [ ] Please update your Readme, currently some headings are missing such as  

``` ##  Getting Started ```

It will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users. Please add descriptive steps from cloning your app to seeing the results displayed on the browser.. This includes `git clone URL` , `cd project_name` etc

- I would also recommend to add the following: 

```
## 🤝 Contributing

Contributions, issues, and feature requests are welcome!

Feel free to check the [issues page](../../issues/).

## Show your support

Give a ⭐️ if you like this project!

## Acknowledgments

- Microverse
```


- please refer to this [template](https://github.com/microverseinc/readme-template), you can copy and paste the content but remember to customize it to your project.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-13 23:27 UTC, BenMukebo commented on app/models/user.rb
> +  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
- [ ] Great job so far 👏🏻 However according to the project requirements, The application should ask for confirmation of user email when a user registers himself. You can check and make sure the  `:confirmable` is enabled in the user model (`user.rb` file). You should look something similar to what is below:

   ```ruby
   	devise :database_authenticatable, :registerable,
   	:recoverable, :rememberable, :validatable, :confirmable
   ```

2022-10-13 23:27 UTC, BenMukebo commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [ ] It looks like your sign-up and login button does not work as shown on the video 👇🏻 by the way my console shows that the user has been successfully created and login however I'm still on the same page. Please address this 👍🏻  

[Screencast from 10-14-2022 01:17:27 AM.webm](https://user-images.githubusercontent.com/79058364/195728004-0f000586-331a-47e5-ac22-53f202f1236d.webm)

2022-10-14 21:06 UTC, MahmoudBakr23 approved these changes
Hi team😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

**Highlights**
- Well done making the required changes from the previous reviewer

**Optional**
- Please make the README file recommendations from the previous reviewer
- Fix the MIT link for a professional README file

Cheers and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-17 16:04 UTC, merged